version: "3.6"
#all port number should be exposed appending 9
services:

  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard
    restart: unless-stopped
    ports:
      - "9090:80"
      - "9443:443"
    depends_on:
      - kanboard-db
    volumes:
      - /home/cevasrv/data/kanboard/data:/var/www/app/data
      - /home/cevasrv/data/kanboard/plugins:/var/www/app/plugins
      - /home/cevasrv/data/kanboard/ssl:/etc/nginx/ssl
    environment:
      DATABASE_URL: postgres://postgres:postgres@kanboard-db:5432/kanboard
    networks:
      - portainer

  kanboard-db:
    image: postgres
    container_name: kanboard-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanboard
      POSTGRES_PASSWORD: CHANGEIT
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /home/cevasrv/data/postgres:/var/lib/postgresql/data
      - /home/cevasrv/Workspace/kanboard/postgres.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - portainer

volumes:
  kanboard:

networks:
  portainer:
    name: portainer
    external: true
